language: node_js
node_js:
  - lts/*

deploy:
  provider: heroku
  api_key:
    secure: YQSsKzmavpFzpefzfb+GQf9gehPdSDBQqcCUtFQENxfbTwCSF49VoQEbT7Akhpv66WtA0Jfnw+hYJlpqyJH+dbLgR7UyuzUoMxY9jJaECrpSP6/qt7tYBmOR4/mcMtGyblTk+E6ccDs/VlQ2QUoNCkS1eGy7YMHuJIv9sbPmv2HTwnBKrnq33PpxQxDkyko0Y7ZHutk8DhI0B2Fv67GOTYCTtK41qpvvoikby2o4UxrDOMn2A+D0uu0PSUj5kpvw05Mpy8yTJjeUWGPHJ/AlpLmUk4EKtnWcpINmzQdtofnchhbJbiqvKTP/bvVSoI/T9n0rcYw8ZHNagIn2kWeQVQ/9mkwSkghEiDi0fJyJgyA8VXCe2J8CfbhHYn+vsCprjlTBo+45nw8Vu3SMRgO0jMKaoQ4LZ5Nho11Sm39Iz8Jp1J+tzUsag0QQpzbS8hMyOQctBKb8gccF2b9YxQy257XNVRMS123wbl3laTVRuZkeFPNCbTUKxyED7GB6Xyi+1gN6IDe9BGOAx7NbelkVgDlWM+FmXepuOShWGOPrr/MpoNcq/B1D1Tn2fAE+/3AJU3Y636/DM2xUeN/BBbxN2Zrb9gFG+w9x7fb25TgkBap/y2Bgj6xZzJVUDcb34mESqZf8vlAD8w/HqQxN0PMtD6I/MsdVN1feT7CRF8CtLNY=
